export enum ServiceCategoryEnum {
  PESTCONTROLL = 'PEST CONTROLL',
  AIRCONDITIONING = 'AIR CONDITIONING',
  ELETRICAL = 'ELETRICAL',
  HOMECARE = 'HOMECARE',
  HYDRAULICS = 'HYDRAULICS',
  TECH = 'TECH',
  PAINTING = 'PAINTING',
  FURNITURE = 'FURNITURE',
  SECURITY = 'SECURITY',
  ACCESSIBILITY = 'ACCESSIBILITY',
  LANDSCAPING = 'LANDSCAPING',
}
